# Generated by Django 4.2 on 2023-04-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transcription_app', '0003_video_video_file_alter_video_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='upload/videos/'),
        ),
    ]
